In [18]:
import pandas as pd

In [19]:
df = pd.read_csv(
    r"E:\Financial_Transaction_Analytics\data\cleaned_data\cleaned_data.csv",parse_dates=["transaction_datetime", "date_of_birth"]
)

In [20]:
df.head()

,transaction_datetime,transaction_id,transaction_unix_time,credit_card_number,customer_name,customer_gender,date_of_birth,customer_job,customer_street,customer_city,...,customer_zip,customer_latitude,customer_longitude,city_population,merchant_name,merchant_category,merchant_latitude,merchant_longitude,transaction_amount,fraud_flag
0,2019-01-01 00:00:18,0b242abb623afc578575680df30655b9,1325376018,2703186189652095,Jennifer Banks,F,1988-03-09,"Psychologist, counselling",561 Perry Cove,Moravian Falls,...,28654,36.0788,-81.1781,3495,"fraud_Rippin, Kub and Mann",misc_net,36.011293,-82.048315,4.97,0
1,2019-01-01 00:00:44,1f76529f8574734946361c461b024d99,1325376044,630423337322,Stephanie Gill,F,1978-06-21,Special educational needs teacher,43039 Riley Greens Suite 393,Orient,...,99160,48.8878,-118.2105,149,"fraud_Heller, Gutmann and Zieme",grocery_pos,49.159047,-118.186462,107.23,0
2,2019-01-01 00:00:51,a1a22d70485983eac12b5b88dad1cf95,1325376051,38859492057661,Edward Sanchez,M,1962-01-19,Nature conservation officer,594 White Dale Suite 530,Malad City,...,83252,42.1808,-112.2620,4154,fraud_Lind-Buckridge,entertainment,43.150704,-112.154481,220.11,0
3,2019-01-01 00:01:16,6b849c168bdad6f867558c3793159a81,1325376076,3534093764340240,Jeremy White,M,1967-01-12,Patent attorney,9443 Cynthia Court Apt. 038,Boulder,...,59632,46.2306,-112.1138,1939,"fraud_Kutch, Hermiston and Farrell",gas_transport,47.034331,-112.561071,45.00,0
4,2019-01-01 00:03:06,a41d7549acf90789359a9aa5346dcb46,1325376186,375534208663984,Tyler Garcia,M,1986-03-28,Dance movement psychotherapist,408 Bradley Rest,Doe Hill,...,24433,38.4207,-79.4629,99,fraud_Keeling-Crist,misc_pos,38.674999,-78.632459,41.96,0

In [21]:
df.dtypes

transaction_datetime     datetime64[us]
transaction_id                      str
transaction_unix_time             int64
credit_card_number                int64
customer_name                       str
customer_gender                     str
date_of_birth            datetime64[us]
customer_job                        str
customer_street                     str
customer_city                       str
customer_state                      str
customer_zip                      int64
customer_latitude               float64
customer_longitude              float64
city_population                   int64
merchant_name                       str
merchant_category                   str
merchant_latitude               float64
merchant_longitude              float64
transaction_amount              float64
fraud_flag                        int64
dtype: object

In [28]:
df["transaction_year"] = df["transaction_datetime"].dt.year
df["transaction_month"] = df["transaction_datetime"].dt.month
df["transaction_month_name"] = df["transaction_datetime"].dt.month_name()
df["transaction_day"] = df["transaction_datetime"].dt.day
df["transaction_day_name"] = df["transaction_datetime"].dt.day_name()
df["transaction_hour"] = df["transaction_datetime"].dt.hour

In [29]:
df.columns

Index(['transaction_datetime', 'transaction_id', 'transaction_unix_time',
       'credit_card_number', 'customer_name', 'customer_gender',
       'date_of_birth', 'customer_job', 'customer_street', 'customer_city',
       'customer_state', 'customer_zip', 'customer_latitude',
       'customer_longitude', 'city_population', 'merchant_name',
       'merchant_category', 'merchant_latitude', 'merchant_longitude',
       'transaction_amount', 'fraud_flag', 'transaction_month',
       'trasaction_year', 'transaction_month_name', 'transaction_day',
       'transaction_day_name', 'transaction_hour', 'transaction_year'],
      dtype='str')

In [31]:
def get_time_of_day(hour):
    if hour>=5 and hour < 12:
        return "Morning"
    elif hour>=12 and hour<17:
        return "Afternoon"
    elif hour>=17 and hour<19:
        return "Evening"
    else:
        return "Night"

In [32]:
df["time_of_day"] = df["transaction_hour"].apply(get_time_of_day)

In [42]:
df.sample(20)[["transaction_hour", "time_of_day"]]

         transaction_hour time_of_day
472733                 12   Afternoon
668888                 14   Afternoon
706737                 13   Afternoon
602761                 14   Afternoon
871284                 15   Afternoon
1070497                18     Evening
689506                  2       Night
588429                  3       Night
199110                 22       Night
121603                 15   Afternoon
862303                 23       Night
1143733                11     Morning
40709                  22       Night
928426                 17     Evening
1088592                22       Night
858886                 22       Night
143921                 18     Evening
163463                 20       Night
919490                 15   Afternoon
1071775                13   Afternoon

In [70]:
def get_weekend(transaction_day_name):
    if transaction_day_name in ["Saturday", "Sunday"]:
        return("weekend")
    else:
        return("weekdays")

In [71]:
df["weekend"] = df["transaction_day_name"].apply(get_weekend)

In [72]:
df.sample(20)["weekend"]

530640     weekdays
7033        weekend
637228      weekend
983784     weekdays
1188905    weekdays
1014925     weekend
1044350    weekdays
1225992    weekdays
975085     weekdays
1226704    weekdays
866853     weekdays
468028     weekdays
478661      weekend
575365      weekend
830008     weekdays
1032796    weekdays
700007      weekend
1045968    weekdays
837467     weekdays
1009252    weekdays
Name: weekend, dtype: str

In [69]:
df["transaction_day_name"].head()

0    Tuesday
1    Tuesday
2    Tuesday
3    Tuesday
4    Tuesday
Name: transaction_day_name, dtype: str

In [87]:
df["customer_age"] =( (df["transaction_datetime"] - df["date_of_birth"])/pd.Timedelta(days = 365.25)).astype(int)

In [88]:
df["customer_age"].head()

0    30
1    40
2    56
3    51
4    32
Name: customer_age, dtype: int64

In [89]:
bins = [0,18,35,50,65,100]
labels = ["Under 18", "18-35","35-50","50-65","65-100"]
df["customer_age_group"] = pd.cut(df["customer_age"],bins = bins, labels = labels,right = True)

In [90]:
df["customer_age_group"].value_counts()

customer_age_group
18-35       423885
35-50       412252
50-65       260900
65-100      178489
Under 18     21149
Name: count, dtype: int64

In [91]:
bins = [0,50,200,500,float("inf")]

labels = ["Low",
          "Medium",
          "High",
          "Very High"]

df["transaction_amount_group"] = pd.cut(df["transaction_amount"],bins = bins, labels = labels)

In [92]:
df.sample(20)["transaction_amount_group"]

268329     Medium
64698         Low
18711         Low
566128     Medium
35406      Medium
1194911    Medium
888509     Medium
700669        Low
470288     Medium
118389     Medium
177849        Low
1045568       Low
230912        Low
1253107       Low
158692     Medium
914959        Low
294942        Low
1228031      High
664944        Low
969446        Low
Name: transaction_amount_group, dtype: category
Categories (4, str): ['Low' < 'Medium' < 'High' < 'Very High']

In [93]:
bins = [0,10000,100000,500000,float("inf")]

labels = ["Small Town",
          "Medium Town",
          "Large Town",
          "Metro"]

df["city_population_group"] = pd.cut(df["city_population"],bins = bins,labels = labels)

In [94]:
df.sample(20)["city_population_group"]

693604     Medium Town
772620      Small Town
140685      Large Town
338455      Small Town
1245221     Small Town
1250469     Small Town
1173926     Small Town
798539      Small Town
282874           Metro
607755           Metro
175097      Small Town
1283579    Medium Town
1165024     Small Town
442331      Small Town
742461      Large Town
552413     Medium Town
440249      Small Town
803692      Small Town
794652      Small Town
1249367     Small Town
Name: city_population_group, dtype: category
Categories (4, str): ['Small Town' < 'Medium Town' < 'Large Town' < 'Metro']

In [95]:
df.to_csv(r"E:\Financial_Transaction_Analytics\data\feature_engineered_data\transactions_feature_engineered.csv",index = False)